# Use the official Debian image from Docker Hub
FROM dakshinatharindu/debian:latest

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies (you can modify this based on your needs)
RUN apt-get update && apt-get install -y \
    sudo \
    git \
    curl \
    vim \
    build-essential \
    python3 \
    python3-pip \
    lsb-release wget software-properties-common gnupg \
    && apt-get clean

RUN bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

# Create a new user with a home directory and set a default shell
RUN useradd -m -s /bin/bash afluser

# Give the new user sudo privileges
RUN echo 'afluser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Switch to afluser and install Rust
USER afluser
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Set the working directory for the user
WORKDIR /home/afluser

# Set the default command to bash (this can be modified as needed)
CMD ["/bin/bash"]
